// swift-tools-version: 5.8

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Demo",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Demo",
            targets: ["AppModule"],
            bundleIdentifier: "com.github.fumito-ito.FirebaseRemoteConfigOpenFeatureProvider.Demo",
            teamIdentifier: "L8LPZ499U7",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .checkmark),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(path: ".."),
        .package(url: "https://github.com/open-feature/swift-sdk", "0.0.2"..<"0.3.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FirebaseRemoteConfigOpenFeatureProvider", package: "firebaseremoteconfig-openfeature-provider-swift"),
                .product(name: "OpenFeature", package: "swift-sdk")
            ],
            path: ".",
            resources: [
                .process("GoogleService-Info.plist")
            ]
        )
    ]
)
